### ISSUE TITLE
[feature request]: center-at-my-location pref

### ISSUE THREAD

**Issue by herrdeh** [k3b/LocationMapViewer#15]
I'm (ab)using this app as a navigator when in need to get an overview at a unknown place. The special charme is its extremely fast launching - a fraction of time what "real" navigators need. 

To make my 100% happy with is, I'd like a preference "always launch with view centered to location". A nice-to have would be "always keep view centered to location".

Anyway - thank you very much for your work!

**Comment by k3b** [comment]
A good idea. It will need some time to add this because i have other projects with higher priorities. 
This will be implemented together with #13.

**Comment by herrdeh** [comment]
By, now, this very nice app does the job:

[OpenTopoMap Viewer](https://pygmalion.nitri.org/opentopomap-viewer-for-android-1208.html)

It does TopoMap and OSM as well.
