### ISSUE TITLE
[bug] LMV is associated with all file types

### ISSUE THREAD

**Issue by danielmmmm** [k3b/LocationMapViewer#2]
I noticed that when I open any file from a file explorer, LMV is always among the suggested apps to open these files. It doesn't matter what kind of file it is. I tried .apk, .zip, .txt, .conf, .bak, .properties, and at least four of them should not be opened with LMV.

**Comment by k3b** [comment]
thanks for the info. The issue is reproducable on my handset, too.

i will analyse the problem tomorrow

**Comment by danielmmmm** [comment]
Thanks for your efforts! :-D
