### ISSUE TITLE
Wrong character encoding in About menu

### ISSUE THREAD

**Issue by pejakm** [k3b/LocationMapViewer#5]
Character encoding for About menu is wrong, therefore, Serbian translation for this view is garbled:

http://www.dodaj.rs/f/2l/42/4uDHdkOl/screenshot2015-05-07-13-.png

**Comment by k3b** [comment]
thanks for info. currently i am on holiday and i have no dev Computer available for the Nest 2 weeks. 

for the german about Text i had To html-escape special Charts linke ü with & uuml ; how is This done with serbian characters?

**Comment by k3b** [comment]
stackoverflow.com/questions/4933069/android-webview-with-garbled-utf-8-characters

This should fix the issue so hopefully there should be no Moore need for escaping
